/**
 * Tile pattern generators.
 *
 * Each generator yields tile polygons for an "infinite" grid that covers
 * a given bounding area + margins. The layout engine then clips these
 * against the room boundary.
 *
 * All generators accept an offset (dx, dy) that the optimizer varies
 * to find the best alignment.
 */

import { Polygon, Room, TileConfig, AlignmentMode } from '../types';
import { rectToPolygon, rotatePolygon } from '../utils/math';

export interface PatternGeneratorParams {
  tileConfig: TileConfig;
  /** Area width to cover (room width) in mm */
  areaWidth: number;
  /** Area height to cover (room height) in mm */
  areaHeight: number;
  /** X offset to shift the entire grid (optimization parameter) */
  offsetX: number;
  /** Y offset to shift the entire grid (optimization parameter) */
  offsetY: number;
}

/**
 * Generate tile polygons for a given pattern.
 * Returns an array of unclipped tile polygons.
 */
export function generateTiles(params: PatternGeneratorParams): Polygon[] {
  const { tileConfig, areaWidth, areaHeight } = params;

  let tiles: Polygon[];
  switch (tileConfig.pattern) {
    case 'grid':
      tiles = generateGrid(params);
      break;
    case 'offset-1/2':
      tiles = generateOffset(params, 0.5);
      break;
    case 'offset-1/3':
      tiles = generateOffset(params, 1 / 3);
      break;
    case 'herringbone':
      tiles = generateHerringbone(params);
      break;
    case 'diagonal-45':
      tiles = generateDiagonal45(params);
      break;
    default:
      tiles = generateGrid(params);
  }

  return tiles;
}

/**
 * Standard grid pattern: tiles placed in a regular grid.
 */
function generateGrid(params: PatternGeneratorParams): Polygon[] {
  const { tileConfig, areaWidth, areaHeight, offsetX, offsetY } = params;
  const tw = tileConfig.width + tileConfig.grout;
  const th = tileConfig.height + tileConfig.grout;
  const tiles: Polygon[] = [];

  // Start from negative margin to cover shifted tiles
  const startX = -tw + (offsetX % tw);
  const startY = -th + (offsetY % th);

  for (let y = startY; y < areaHeight + th; y += th) {
    for (let x = startX; x < areaWidth + tw; x += tw) {
      tiles.push(rectToPolygon(x, y, tileConfig.width, tileConfig.height));
    }
  }

  return tiles;
}

/**
 * Offset pattern: even rows are shifted by `fraction` of the tile width.
 * fraction=0.5 → 1/2 offset (brick bond)
 * fraction=1/3 → 1/3 offset
 */
function generateOffset(
  params: PatternGeneratorParams,
  fraction: number
): Polygon[] {
  const { tileConfig, areaWidth, areaHeight, offsetX, offsetY } = params;
  const tw = tileConfig.width + tileConfig.grout;
  const th = tileConfig.height + tileConfig.grout;
  const tiles: Polygon[] = [];

  const startX = -tw * 2 + (offsetX % tw);
  const startY = -th + (offsetY % th);

  let rowIndex = 0;
  for (let y = startY; y < areaHeight + th; y += th) {
    const rowOffset = (rowIndex % 2 === 1) ? tw * fraction : 0;
    for (let x = startX + rowOffset; x < areaWidth + tw * 2; x += tw) {
      tiles.push(rectToPolygon(x, y, tileConfig.width, tileConfig.height));
    }
    rowIndex++;
  }

  return tiles;
}

/**
 * Herringbone pattern — the classic 45° interlocking weave.
 *
 * The weave is built from L-shaped blocks, each a long tile (w × h) with a
 * short tile (h × w) standing on its upper-left corner:
 *
 *   H tile: rect at (P.x, P.y),     size w × h
 *   V tile: rect at (P.x, P.y + S), size h × w     (S = h + g)
 *
 * Blocks repeat on the lattice generated by
 *   t1 = (S,  S)
 *   t2 = (2S, −2S)
 * which tiles the plane exactly (no gaps/overlaps) when L = 2S, i.e. the
 * standard 2:1 herringbone tile (w + g = 2·(h + g)). Other ratios still
 * render the same weave with grout-line drift proportional to the mismatch.
 *
 * The whole lattice is then rotated −45° about the area centre so the braids
 * run horizontally, giving the diagonal herringbone look.
 */
function generateHerringbone(params: PatternGeneratorParams): Polygon[] {
  const { tileConfig, areaWidth, areaHeight, offsetX, offsetY } = params;
  const w = tileConfig.width;
  const h = tileConfig.height;
  const g = tileConfig.grout;
  const tiles: Polygon[] = [];

  const S = h + g; // effective short side
  const L = w + g; // effective long side
  if (S <= 0) return tiles;

  const center = { x: areaWidth / 2, y: areaHeight / 2 };
  const angle = -Math.PI / 4; // braids run horizontally

  // Cover the room's circumscribed circle before rotation, plus tile extent.
  const diagonal = Math.sqrt(areaWidth * areaWidth + areaHeight * areaHeight);
  const R = diagonal / 2 + L + S;

  // Lattice origin (the optimizer shifts the weave via offsetX/offsetY).
  const ox = center.x + offsetX;
  const oy = center.y + offsetY;

  // Invert the lattice to find which (a, b) blocks land inside the coverage
  // square [center ± R]. P − origin = a·t1 + b·t2 ⇒
  //   a = (dx + dy) / (2S),  b = (dx − dy) / (4S)
  let aMin = Infinity, aMax = -Infinity, bMin = Infinity, bMax = -Infinity;
  for (const cx of [center.x - R, center.x + R]) {
    for (const cy of [center.y - R, center.y + R]) {
      const dx = cx - ox;
      const dy = cy - oy;
      const a = (dx + dy) / (2 * S);
      const b = (dx - dy) / (4 * S);
      aMin = Math.min(aMin, a);
      aMax = Math.max(aMax, a);
      bMin = Math.min(bMin, b);
      bMax = Math.max(bMax, b);
    }
  }
  // Pad to account for a block extending up to L beyond its lattice point.
  const pad = 2;
  aMin = Math.floor(aMin) - pad;
  aMax = Math.ceil(aMax) + pad;
  bMin = Math.floor(bMin) - pad;
  bMax = Math.ceil(bMax) + pad;

  for (let a = aMin; a <= aMax; a++) {
    for (let b = bMin; b <= bMax; b++) {
      const px = ox + a * S + b * 2 * S;
      const py = oy + a * S - b * 2 * S;
      // Long (horizontal) tile + short (vertical) tile standing on its corner.
      const hTile = rectToPolygon(px, py, w, h);
      const vTile = rectToPolygon(px, py + S, h, w);
      tiles.push(rotatePolygon(hTile, center, angle));
      tiles.push(rotatePolygon(vTile, center, angle));
    }
  }

  return tiles;
}

/**
 * 45° diagonal pattern: entire grid rotated 45°.
 * Tiles are placed in a grid and then the whole grid is rotated 45°
 * around the room center.
 */
function generateDiagonal45(params: PatternGeneratorParams): Polygon[] {
  const { tileConfig, areaWidth, areaHeight, offsetX, offsetY } = params;
  const tw = tileConfig.width + tileConfig.grout;
  const th = tileConfig.height + tileConfig.grout;
  const tiles: Polygon[] = [];

  const centerX = areaWidth / 2;
  const centerY = areaHeight / 2;
  const center = { x: centerX, y: centerY };
  const angle = Math.PI / 4; // 45 degrees

  // Need a larger coverage area since rotation shifts tiles
  const diagonal = Math.sqrt(areaWidth * areaWidth + areaHeight * areaHeight);
  const margin = diagonal;

  const startX = centerX - margin + (offsetX % tw);
  const startY = centerY - margin + (offsetY % th);

  for (let y = startY; y < centerY + margin; y += th) {
    for (let x = startX; x < centerX + margin; x += tw) {
      const tile = rectToPolygon(x, y, tileConfig.width, tileConfig.height);
      const rotated = rotatePolygon(tile, center, angle);
      tiles.push(rotated);
    }
  }

  return tiles;
}

/** Positive modulo. */
function mod(a: number, n: number): number {
  return ((a % n) + n) % n;
}

/**
 * Compute the grid offset that aligns the layout to the room:
 *  - `center-tile`: a full tile is centered on the room center
 *  - `center-grout`: a grout joint runs through the room center
 *
 * Offsets are derived from the basic tile period (width/height + grout),
 * which is exact for grid / running-bond layouts and a sensible best-effort
 * for the others (the grout-center case sits half a tile period away from
 * the tile-center case).
 */
export function computeAlignmentOffset(
  room: Room,
  config: TileConfig,
  mode: Exclude<AlignmentMode, 'optimize'>
): { offsetX: number; offsetY: number } {
  const tw = config.width + config.grout;
  const th = config.height + config.grout;

  // Offset that lands a tile's center on the room center.
  const tileX = mod(room.width / 2 - config.width / 2, tw);
  const tileY = mod(room.height / 2 - config.height / 2, th);

  if (mode === 'center-tile') {
    return { offsetX: tileX, offsetY: tileY };
  }

  // A grout joint sits half a tile period from a tile center.
  return {
    offsetX: mod(tileX - tw / 2, tw),
    offsetY: mod(tileY - th / 2, th),
  };
}

/**
 * Get the pattern-specific unit dimensions for offset calculations.
 */
export function getPatternUnit(config: TileConfig): { unitX: number; unitY: number } {
  const tw = config.width + config.grout;
  const th = config.height + config.grout;

  switch (config.pattern) {
    case 'grid':
    case 'offset-1/2':
    case 'offset-1/3':
    case 'diagonal-45':
      return { unitX: tw, unitY: th };
    case 'herringbone':
      // The weave lattice contains the axis-aligned vectors (4S, 0) and
      // (0, 4S) with S = h + g, so the offset is periodic with 4S in each
      // axis (pre-rotation). Searching one 4S × 4S cell covers every config.
      return {
        unitX: 4 * th,
        unitY: 4 * th,
      };
    default:
      return { unitX: tw, unitY: th };
  }
}
